### ISSUE TITLE
Initial Prototype 

### ISSUE THREAD

**Issue by AkankshaBodhankar** [systers/PCSA-web#4]
This is a initial mockup for the project. Feel free to give suggestions. Thank you 
[mockup PCSA initial.pdf](https://github.com/systers/PCSA-web/files/261908/mockup.PCSA.initial.pdf)

**Comment by MeepyMay** [comment]
[mockup initial.pdf](https://github.com/systers/PCSA-web/files/282412/mockup.initial.pdf)
[diagrams PCSA.pdf](https://github.com/systers/PCSA-web/files/282416/diagrams.PCSA.pdf)

**Comment by choquette33** [comment]
@AkankshaBodhankar - Nice progress! I found the diagrams easy to follow and understand. 

Initial Log-in :  It will be difficult for volunteers to enter their PCVID number, since it is not something that they commonly use or know off the top of their head. With other applications we bulk uploaded a list of users with their emails. This sends them a "welcome email" that includes a token for setting their passwords. This app utilizes that user registration flow:  https://github.com/peacecorps/BonVoyage

All for know, but I'll keep thinking.... thanks!

**Comment by AkankshaBodhankar** [comment]
Hi,
Hope  you are doing well!
Thanks for clearing the  doubts. Found the repository 'Bon voyage' really
helpful.
Regards,
Akanksha

**Comment by AkankshaBodhankar** [comment]
@choquette33 @MeepyMay 
there is a registration page in the initial prototype document mentioned above where the name and password can be taken from the volunteer via the application and the volunteer can sign in using those credentials. A verification email will be sent to the volunteers personal email to confirm. Something similar to facebook where registration is done and then those credentials are used. Sould i go ahead and implement the log in in this manner?

this is the registration

![registration](https://cloud.githubusercontent.com/assets/14356938/15673870/290e0c88-2757-11e6-8f54-23599631fc17.png)
 
This is the log in 
![login with pwd](https://cloud.githubusercontent.com/assets/14356938/15673881/383250f2-2757-11e6-815d-e3ca792dc561.png)



Also, the welcome to recommended pages has four options where will they lead to ? 

![recommended pages](https://cloud.githubusercontent.com/assets/14356938/15673859/1be88e3e-2757-11e6-8870-415dfc602f3b.png)
